# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20170821_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='shots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
